language: python
python:
- '2.7'
- '3.6'
env:
- DJANGO="django>=1.11,<2.0"
- DJANGO="django>=2.0,<3.0"
install:
- pip install -r requirements/test.txt
- pip install coverage coveralls
- pip install $DJANGO
script:
- py.test tests --cov passwords
matrix:
  exclude:
  - python: '2.7'
    env: DJANGO="django>=2.0,<3.0"
  - python: '3.6'
    env: DJANGO="django>=1.11,<2.0"
after_success:
- coverage report
- coveralls
notifications:
  email:
    recipients:
    - maccesch@web.de
deploy:
  provider: pypi
  user: maccesch
  password:
    secure: NoM2NEezIgizj/Q8JeezHKDDNzYsJCEBGIVJ3gAqSIhsq71hWBiA5coautBq214zIXR9P8WlX5ZzEvdEiZJc/u6jgL9Ggp2YOsi5fjGqbAdiGvlPd6lAfgnlbdNqJgjkTEckktiQEmiZYmZGz8tE57In7+BDIuxEg2QWX9eQ21E=
  on:
    tags: true
    repo: dstufft/django-passwords
